# Multi-process container for Next.js, Express, and Nginx on Hugging Face Spaces
FROM node:20-slim

# Install Nginx and utility packages
RUN apt-get update && apt-get install -y \
    nginx \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/*

# Grant permissions to allow running Nginx and writing logs/PIDs as non-root user 1000
RUN chmod -R 777 /var/log/nginx /var/lib/nginx /var/log /run /etc/nginx

WORKDIR /app

# --- 1. Build Backend ---
WORKDIR /app/backend
COPY backend/package*.json ./
COPY backend/prisma/ ./prisma/
RUN npm ci

COPY backend/ ./
# Generate Prisma Client (already generated by postinstall, but good to ensure consistency if schema changes)
RUN npx prisma generate

# --- 2. Build Frontend ---
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./
# Build Next.js
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# --- 3. Finalize setup ---
WORKDIR /app
COPY database/ /app/database/
COPY nginx.conf /app/nginx.conf
COPY start.sh /app/start.sh

# Ensure script is executable and directories are writable by user 1000
RUN chmod +x /app/start.sh && chmod -R 777 /app

# Hugging Face runs containers under user 1000 (non-root)
USER 1000

# Hugging Face Spaces requires the container to listen on port 7860
EXPOSE 7860

CMD ["/app/start.sh"]
